---
title: "Untitled"
author: "Gianluca"
date: "2026-02-06"
output: html_document
---

# Setup (Packgages, Data)
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(ComplexHeatmap)
  library(circlize)
  library(RColorBrewer)
  library(rphylopic)
  library(grid)
  library(ggplot2)
  library(cowplot)
})

# Load data 
setwd("//wsl.localhost/Ubuntu/home/gianl/piezo1_pipeline/all_vs_all_blastp/final_rodentia_piezo1_set_results/")

pairwise <- read_tsv("species_pairwise_matrix.tsv")

setwd("//wsl.localhost/Ubuntu/home/gianl/piezo1_pipeline/data_analysis/taxonomy_files/")

clades <- read_tsv("rodentia_species_clade_mapping.tsv",
                   col_names = c("Species", "Clade"))

# Format correctly clade file for consistency
clades <- clades %>%
  mutate(Species = str_trim(Species),
         Clade = str_trim(Clade))

# Convert column clade data into a vector
clade_lookup <- deframe(clades)

```

# Building the matrix
```{r}
# Make matrix with pairwise identity values

all_species <- sort(unique(c(pairwise$Species_1, pairwise$Species_2)))
n <- length(all_species)

labels <- gsub("_", " ", all_species)

mat <- matrix(100, nrow = n, ncol = n,
              dimnames = list(all_species, all_species))

for (i in seq_len(nrow(pairwise))) {
  s1 <- pairwise$Species_1[i]
  s2 <- pairwise$Species_2[i]
  val <- pairwise$Mean_Identity[i]
  mat[s1, s2] <- val
  mat[s2, s1] <- val
}

# Convert to a distance matrix
dist_mat <- as.dist(100 - mat)

# Clade annotation
clade_for_species <- clade_lookup[all_species]

annotation_row <- data.frame(
  Clade = factor(clade_for_species),
  row.names = all_species
)

clade_colours <- c(
  "Myomorpha" = "#E41A1C",
  "Hystricomorpha" = "#377EB8",
  "Castorimorpha" = "#4DAF4A",
  "Sciuromorpha" = "#FF7F00",
  "Anomaluromorpha" = "#984EA3"
  )

# Primates
#"Hominoidea"       = "#E41A1C",
#"Cercopithecoidea"  = "#377EB8",
#"Platyrrhini"       = "#4DAF4A",
#"Strepsirrhini"     = "#FF7F00",
#"Tarsiidae"      = "#984EA3"

# Rodentia
# "Myomorpha" = "#E41A1C",
#  "Hystricomorpha" = "#377EB8",
#  "Castorimorpha" = "#4DAF4A",
#  "Sciuromorpha" = "#FF7F00",
#  "Anomaluromorpha" = "#984EA3"

# Artiodactyla
# "Ruminantia" = "#E41A1C",
# "Tylopoda" = "#377EB8",
# "Suina" = "#4DAF4A",
# "Whippomorpha" = "#FF7F00"

# Carnivora
# "Canidae" = "#E41A1C",
# "Musteloidea" = "#377EB8"
# "Pinnipedia" = "#4DAF4A",
# "Ursidae" = "#FF7F00",
# "Felidae" = "#984EA3",
# "Eupleridae" = 
# "Herpestidae" =
# "Hyaenidae" =
# "Viverridae" =

clade_pics <- c(
  "Myomorpha" = "dd0a795e-4be3-4f99-a084-2427c1319d31",
  "Hystricomorpha" = "afcfa5fd-3dda-4037-a2e9-9af58a5d3d4b",
  "Castorimorpha" = "be8670c2-a5bd-4b44-88e8-92f8b0c7f4c6",
  "Sciuromorpha" = "23c700c9-e695-404a-8d0c-146e1fc4bada",
  "Anomaluromorpha" = "67800073-0088-44b8-a9f5-a9e960009888"
  )

# Primates
#"Hominoidea"       = "142e0571-3b5f-443d-a887-b572a224ea22",
#"Cercopithecoidea"  = "5f7d2e79-8d60-463d-9087-aacb5a4942ab",
#"Platyrrhini"       = "156b515d-f25c-4497-b15b-5afb832cc70c",
#"Strepsirrhini"     = "8a187391-82a3-4d9b-a402-3a310bf7dc38",
#"Tarsiidae"      = "f598fb39-facf-43ea-a576-1861304b2fe4"

# Rodentia
# "Myomorpha" = "dd0a795e-4be3-4f99-a084-2427c1319d31",
#  "Hystricomorpha" = "afcfa5fd-3dda-4037-a2e9-9af58a5d3d4b",
#  "Castorimorpha" = "be8670c2-a5bd-4b44-88e8-92f8b0c7f4c6",
#  "Sciuromorpha" = "23c700c9-e695-404a-8d0c-146e1fc4bada",
#  "Anomaluromorpha" = "67800073-0088-44b8-a9f5-a9e960009888"

# Artiodactyla
# "Ruminantia" = "dc5c561e-e030-444d-ba22-3d427b60e58a",
# "Tylopoda" = "93c5e5b0-6606-4e10-97e8-699156c57042",
# "Suina" = "9108ee62-1abe-4d45-8803-ab05ae9486c2",
# "Whippomorpha" = "16969246-31e0-48e3-90ff-cad9a8746073"

# Carnivora
# "Canidae" = "8db421ba-4b42-4bd8-b948-5214ce122f57",
# "Musteloidea" = "8f846edb-fa41-41a9-ae7a-dba9598bfe87",
# "Pinnipedia" = "41d9f21e-7e0b-42d2-a088-e154bfa63984",
# "Ursidae" = "369a7880-4798-41bf-851a-ec5da17fafa3",
# "Felidae" = "cc22d71c-a014-41a9-aaf1-5f2cffad6121",
# "Eupleridae" = "7546aa75-8b04-4025-975c-7472c1f7fa5f",
# "Herpestidae" = "2c35b949-4aad-4dd7-a728-5f650e4060d2",
# "Hyaenidae" = "efd94e33-3966-4808-af47-3c58b333f9af",
# "Viverridae" = "2c26a751-162c-469f-a9a4-204e7b7e3ad7"


annotation_colours <- list(Clade = clade_colours)

```

# Plot
```{r}
# Color function
col_fun <- colorRamp2(
  seq(75, 100, length.out = 9),
  rev(brewer.pal(9, "RdYlBu"))
)

# Row/column annotation
ha <- HeatmapAnnotation(
  Clade = clade_for_species,
  col = list(Clade = clade_colours),
  show_legend = FALSE,
  show_annotation_name = FALSE,
  annotation_height = unit(8, "mm")
)

ra <- rowAnnotation(
  Clade = clade_for_species,
  col = list(Clade = clade_colours),
  show_legend = FALSE,
  show_annotation_name = FALSE,
  annotation_width = unit(8, "mm")
)

# Heatmap
ht <- Heatmap(
  mat,
  name = "Identity (%)",
  col = col_fun,
  cluster_rows = hclust(dist_mat, method = "average"),
  cluster_columns = hclust(dist_mat, method = "average"),
  show_row_names = FALSE,
  show_column_names = FALSE,
  show_row_dend = FALSE,
  show_column_dend = FALSE,
  top_annotation = ha,
  left_annotation = ra,
  column_title = "PIEZO1 Pairwise Protein Sequence Identity (%)",
  column_title_gp = gpar(fontsize = 20, fontface = "bold"),
  heatmap_legend_param = list(
    legend_height = unit(10, "cm"),
    legend_width = unit(2, "cm"),
    grid_width = unit(1, "cm"),
    title_gp = gpar(fontsize = 14, fontface = "bold"),
    labels_gp = gpar(fontsize = 12),
    title_position = "topleft"
  )
)

# --- Extract row order ---
ht_drawn <- draw(ht)
ro <- row_order(ht_drawn)

ordered_species <- colnames(mat)[ro]
ordered_clades <- clade_for_species[ordered_species]
n_species <- length(ordered_species)

# Silhouette positions set manually
clade_order <- c("Castorimorpha", "Hystricomorpha", "Sciuromorpha", "Anomaluromorpha", "Myomorpha")
n_clades <- length(clade_order)

padding <- n_species * 0.05

pics_df <- data.frame(
  clade = clade_order,
  y_plot = seq(from = n_species - padding, to = padding, length.out = n_clades),
  uuid = clade_pics[clade_order],
  color = clade_colours[clade_order],
  sil_size = c(1, 1, 1, 1, 1)
)

# Silhouette sizes for each taxonomic order
# Carnivora <- c(2.5, 2.75, 3, 2, 2, 2, 3, 2, 2.75)
# Rodentia
# Cetartiodactyla
# Primates

# Silhouette panel
plot_with_pics <- ggplot(pics_df, aes(x = 0.5, y = y_plot)) +
  geom_phylopic(aes(uuid = uuid, color = color), width = 3) +
  scale_size_identity() +
  geom_text(aes(x = -1.5, y = y_plot, label = clade),
            size = 5, fontface = "bold.italic", hjust = 1) +
  scale_color_identity() +
  scale_y_continuous(
    limits = c(-1.5, n_species + 0.5),
    expand = c(0, 0)
  ) +
  xlim(-5, 2) +
  theme_void()

# Capture heatmap as grob
grob_ht <- grid.grabExpr(draw(ht), wrap = TRUE)

# Combine and save
plot_heatmap <- ggdraw() + draw_grob(grob_ht)
plot <- plot_grid(plot_with_pics, plot_heatmap, nrow = 1, rel_widths = c(0.25, 1))

ggsave(plot = plot,
       filename = "cetartiodactyla_piezo1_heatmap_with_silhouettes_170526.png",
       path = "//wsl.localhost/Ubuntu/home/gianl/piezo1_pipeline/data_analysis/plots",
       width = 17,
       height = 14
)
```
